name: todositos
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_loggy_dio: ^3.0.1
  freezed: ^2.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  hooks_riverpod: ^2.3.5
  injectable: ^2.1.1
  intl: ^0.17.0
  loggy: ^2.0.3

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.4
  flutter_gen_runner: ^5.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  husky: ^0.1.6
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+2
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  generate: true
